IDIR =.
CC = gcc
CFLAGS = -DSTANDALONE -DCREATE_FILES -ggdb -O0 -I$(IDIR)

ODIR = obj
LDIR =

LIBS =

_DEPS = lodepng.h
DEPS = $(patsubst %,$(IDIR)/%,$(_DEPS))

_OBJ = lodepng.o png_fifo_chunker.o 
OBJ = $(patsubst %,$(ODIR)/%,$(_OBJ))

default: png_fifo_chunker

$(ODIR)/%.o: %.c $(DEPS)
	mkdir -p $(ODIR)
	$(CC) -c -o $@ $< $(CFLAGS)

png_fifo_chunker: $(OBJ)
	gcc -o $@ $^ $(CFLAGS) $(LIBS)

.PHONY: clean

clean:
	rm -f *~ core $(INCDIR)/*~
	rm -rf $(ODIR)
